version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '15:00'
    assignees:
      - 'QingqiShi'
    open-pull-requests-limit: 10
    versioning-strategy: increase
    ignore:
      - dependency-name: '@types/node'
        versions: ['>14']
      - dependency-name: 'ts-loader'
        versions: ['>8']
      - dependency-name: 'd3-array'
        versions: ['>2']

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '15:00'
    assignees:
      - 'QingqiShi'
    open-pull-requests-limit: 10
